ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_subscribed     BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS subscribed_at     TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS subscribed_until  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50);
